/* $OpenBSD: version.h,v 1.73 2015/07/01 01:55:13 djm Exp $ */
#define SSH_VERSION	"OpenSSH_6.9"

#define SSH_PORTABLE	"p2"
#define SSH_HPN         "-hpn14v9"
#define SSH_RELEASE	SSH_VERSION SSH_PORTABLE SSH_HPN

#ifdef NERSC_MOD
#undef SSH_RELEASE
#define SSH_AUDITING	"NMOD_3.17"
#define SSH_RELEASE	SSH_VERSION SSH_PORTABLE SSH_HPN SSH_AUDITING
#endif /* NERSC_MOD */
