/* $OpenBSD: version.h,v 1.85 2019/10/09 00:04:57 djm Exp $ */

#define SSH_VERSION	"OpenSSH_8.1"

#define SSH_PORTABLE	"p1"
#define SSH_HPN         "-hpn14v20"
#define SSH_RELEASE	SSH_VERSION SSH_PORTABLE SSH_HPN

#ifdef NERSC_MOD
#undef SSH_RELEASE
#define SSH_AUDITING	"NMOD_3.19"
#define SSH_RELEASE	SSH_VERSION SSH_PORTABLE SSH_HPN SSH_AUDITING
#endif /* NERSC_MOD */
